/**
 * dspack contract → generated json-render modules (TypeScript source text).
 *
 *   catalog.ts   — defineCatalog(schema, …) with Zod prop schemas compiled
 *                  from the contract's prop vocabulary (enums verbatim).
 *   registry.tsx — defineRegistry(catalog, …) with typed stub renderers, one
 *                  per catalog component. Stubs exist so the registry's
 *                  catalog-inferred prop typing is *compiled*, not assumed
 *                  (gate J1); consumers replace them with real components.
 *
 * The generators emit source text only — this module has no runtime
 * dependency on @json-render/* or zod. The generated modules are compiled
 * and executed in gates/json-render, which pins those packages (the a2ui
 * side of the repo is pinned to zod v3 via @a2ui/web_core, so the zod v4
 * packages json-render requires cannot live in the root dependency tree).
 *
 * All props are `.nullable()`: CSR props are optional, and json-render's
 * catalog idiom prefers nullable over optional for structured-output
 * compatibility.
 */
import type { DspackDoc } from "../../types.js";
import { buildCatalogModel, type CatalogComponent, type CatalogModel, type CatalogProp } from "./model.js";
import { shadcnJsonRenderProfile, type JsonRenderProfile } from "./profile.js";

export interface JsonRenderModules {
  /** Source text of the generated catalog module (catalog.ts). */
  catalogTs: string;
  /** Source text of the generated registry module (registry.tsx). */
  registryTsx: string;
  /** The model both modules were rendered from. */
  model: CatalogModel;
}

export function generateJsonRenderModules(
  doc: DspackDoc,
  profile: JsonRenderProfile = shadcnJsonRenderProfile,
): JsonRenderModules {
  const model = buildCatalogModel(doc, profile);
  return {
    catalogTs: renderCatalogModule(model, doc),
    registryTsx: renderRegistryModule(model, doc),
    model,
  };
}

function header(what: string, doc: DspackDoc): string {
  return (
    `/**\n` +
    ` * GENERATED ${what} — do not edit.\n` +
    ` * Generated by dspack-to-a2ui (--target json-render) from the dspack contract\n` +
    ` * ${JSON.stringify(doc.name)} (dspack ${JSON.stringify(doc.dspack)}).\n` +
    ` */\n`
  );
}

export function renderCatalogModule(model: CatalogModel, doc: DspackDoc): string {
  const lines: string[] = [];
  lines.push(header("json-render catalog", doc).trimEnd());
  lines.push(`import { defineCatalog } from "@json-render/core";`);
  lines.push(`import { schema } from "@json-render/react/schema";`);
  lines.push(`import { z } from "zod";`);
  lines.push(``);
  lines.push(`export const catalog = defineCatalog(schema, {`);
  lines.push(`  components: {`);
  for (const component of model.components) {
    for (const excluded of component.excludedProps) {
      lines.push(`    // ${component.dspackId}.${excluded.name} excluded: ${excluded.reason}`);
    }
    lines.push(`    ${component.name}: {`);
    lines.push(`      props: z.object({`);
    for (const prop of component.props) {
      lines.push(`        ${propKey(prop.name)}: ${zodExpr(prop)},`);
    }
    lines.push(`      }),`);
    // Every component accepts children: the CSR node schema allows children
    // on any node (composition correctness is gate S3's job, pre-emission).
    lines.push(`      slots: ["default"],`);
    lines.push(`      description: ${JSON.stringify(component.description)},`);
    lines.push(`    },`);
  }
  lines.push(`  },`);
  lines.push(`  actions: {},`);
  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

export function renderRegistryModule(model: CatalogModel, doc: DspackDoc): string {
  const lines: string[] = [];
  lines.push(header("json-render registry (stub implementations)", doc).trimEnd());
  lines.push(`import { defineRegistry } from "@json-render/react";`);
  lines.push(`import { catalog } from "./catalog.js";`);
  lines.push(``);
  lines.push(`export const { registry } = defineRegistry(catalog, {`);
  lines.push(`  components: {`);
  for (const component of model.components) {
    lines.push(`    ${component.name}: ({ props, children }) => (`);
    lines.push(`      <div data-dspack=${JSON.stringify(component.dspackId)}>`);
    lines.push(`        {props.text}`);
    lines.push(`        {children}`);
    lines.push(`      </div>`);
    lines.push(`    ),`);
  }
  lines.push(`  },`);
  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function zodExpr(prop: CatalogProp): string {
  let base: string;
  switch (prop.kind) {
    case "enum":
      base = `z.enum([${prop.values!.map((v) => JSON.stringify(v)).join(", ")}])`;
      break;
    case "string":
      base = `z.string()`;
      break;
    case "boolean":
      base = `z.boolean()`;
      break;
    case "number":
      base = `z.number()`;
      break;
  }
  const described = prop.description ? `${base}.describe(${JSON.stringify(prop.description)})` : base;
  return `${described}.nullable()`;
}

// Re-exported for callers that only need naming/vocabulary (e.g. tests).
export type { CatalogComponent };
